In [1]:
lst = [1, 2, 3, 4, 5]

lst

[1, 2, 3, 4, 5]

In [2]:
lst[2] = '문자열'

lst

# 파이썬 컨테이너는 서로 다른 종류의 값이 저장되는 것을 막지 못함
# 넘피는 같은 종류의 값으로만 저장이 가능함

[1, 2, '문자열', 4, 5]

In [1]:
# 다차원 구조 지원하지만 안정적이지 못함

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for sub in lst:
    for num in sub:
        print(num, end='\t')
        
    print()

1	2	3	
4	5	6	
7	8	9	


In [2]:
# 안정적 X

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

lst[1] = '나는 문자열'

for sub in lst:
    for num in sub:
        print(num, end='\t')
        
    print()

1	2	3	
나	는	 	문	자	열	
7	8	9	


In [3]:
# 안정적 X

lst[1] = 1234
for sub in lst:
    for num in sub:
        print(num, end='\t')
        
    print()

1	2	3	


TypeError: 'int' object is not iterable

In [1]:
import numpy as np

In [ ]:
'''
Sequential Container
=> str, list, tuple / index(o), slicing(o)

Non-Sequential Container
=> set, dict / index(x)
----------------------------
str, list, tuple, set, dict
'''

In [5]:
lst1 = [1, 2, 3, 4, 5]
arr1 = np.array(lst1)

print(type(lst1), type(arr1))
arr1

#ndarray: n차원(dimension)array

<class 'list'> <class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [3]:
print(type(3), type(3.), type(.3))

<class 'int'> <class 'float'> <class 'float'>


In [6]:
# numpy 배열은 하나라도 실수면 전부 실수로 바꿔 실수 배열이 됨

lst2 = [1.2, 2, 3, 4, 5.3]
arr2 = np.array(lst2)

print(type(lst2), type(arr2))
arr2

<class 'list'> <class 'numpy.ndarray'>


array([1.2, 2. , 3. , 4. , 5.3])

In [7]:
print(arr1.dtype, arr2.dtype)

# C언어에서 정수는 4바이트 int가 기본 -> 32bit
# C언어에서 실수는 8바이트, double과 같음

int32 float64


In [8]:
# 다차원 배열
lst3 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr3 = np.array(lst3)

arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [10]:
# step 생략 가능
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# start 생략 가능
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# stop 생략하면 오류 발생
arr = np.arange()
arr

TypeError: arange() requires stop to be specified.

In [ ]:
'''
넘피의 함수: array, arange, linspace, ones, zeros, eye
배열의 속성: dtype, shape
배열의 메서드: reshape, astype
'''

In [13]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
arr.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
# 합쳐서 표현할 수도 있음
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
arr = np.arange(12)
arr.reshape(4, 3)    # reshape 메서드는 원본 배열을 변경하지 않는다.

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
arr1 = np.arange(12)
arr2 = arr.reshape(4, 3)    # reshape 메서드는 꼭 저장해서 사용해야 함

print(arr1, arr2, sep='\n\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
arr1 = np.arange(12) # arr1 - 12개
arr2 = arr1.reshape(4, 4) # arr2 - 16개라 오류 발생

ValueError: cannot reshape array of size 12 into shape (4,4)

In [22]:
# 원본 배열에 저장된 값의 수와 새로운 배열에서 필요로 하는 값의 수가 반드시 일치해야 함. 많거나 적으면 오류 발생.

arr1 = np.arange(12)
arr2 = arr1.reshape(3, 3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [24]:
arr1 = np.arange(12)
arr2 = arr.reshape(4, 3)

print(arr1.shape, arr2.shape)

# shape 속성의 결과는 튜플임 (x, y)
# arr1은 1차원 배열이기 때문에 크기가 12인 1차원 배열
# 단일값 튜플을 허용하지 않지만 만들 수는 있음. 그럴 때 콤마 사용

(12,) (4, 3)


In [28]:
tpl1 = (3)
print(type(tpl1), tpl1)

<class 'int'> 3


In [29]:
tpl2 = (3,)
print(type(tpl2), tpl2, tpl2[0])

<class 'tuple'> (3,) 3


In [31]:
arr1 = np.linspace(1, 10, 10)
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
np.pi

3.141592653589793

In [34]:
arr2 = np.linspace(0, np.pi, 20)
arr2

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [35]:
# num 생략하면 50개
arr2 = np.linspace(0, np.pi)
arr2

array([0.        , 0.06411414, 0.12822827, 0.19234241, 0.25645654,
       0.32057068, 0.38468481, 0.44879895, 0.51291309, 0.57702722,
       0.64114136, 0.70525549, 0.76936963, 0.83348377, 0.8975979 ,
       0.96171204, 1.02582617, 1.08994031, 1.15405444, 1.21816858,
       1.28228272, 1.34639685, 1.41051099, 1.47462512, 1.53873926,
       1.60285339, 1.66696753, 1.73108167, 1.7951958 , 1.85930994,
       1.92342407, 1.98753821, 2.05165235, 2.11576648, 2.17988062,
       2.24399475, 2.30810889, 2.37222302, 2.43633716, 2.5004513 ,
       2.56456543, 2.62867957, 2.6927937 , 2.75690784, 2.82102197,
       2.88513611, 2.94925025, 3.01336438, 3.07747852, 3.14159265])

In [36]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
arr3 = np.ones(10)
arr3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
num_str = '1.567 0.123 5.6789 5 8.456 3 9.345'
lst = num_str.split(' ')
arr1 = np.array(lst)
arr1

# <U6에서 U: Unicode 문자열, 6: 제일 긴 문자열 길이가 6자리

array(['1.567', '0.123', '5.6789', '5', '8.456', '3', '9.345'],
      dtype='<U6')

In [46]:
arr1.astype(float)
# astype는 원본 배열을 변경하지 않음, 따로 저장 필요

array([1.567 , 0.123 , 5.6789, 5.    , 8.456 , 3.    , 9.345 ])

In [47]:
arr1

array(['1.567', '0.123', '5.6789', '5', '8.456', '3', '9.345'],
      dtype='<U6')

In [49]:
num_str = '1.567 0.123 5.6789 5 8.456 3 9.345'
lst = num_str.split(' ')
arr1 = np.array(lst)
arr2 = arr1.astype(float) # float은 numpy가 아니라 python의 데이터 타입임

print(arr1.dtype, arr1)
print(arr2.dtype, arr2)

<U6 ['1.567' '0.123' '5.6789' '5' '8.456' '3' '9.345']
float64 [1.567  0.123  5.6789 5.     8.456  3.     9.345 ]


In [52]:
num_str = '1.567 0.123 5.6789 5 8.456 3 9.345'
lst = num_str.split(' ')
arr1 = np.array(lst)
arr2 = arr1.astype(np.float32) # 64가 아니라 32로 하면 정밀도는 떨어지지만 데이터 양이 1/2가 됨

print(arr1.dtype, arr1)
print(arr2.dtype, arr2)

<U6 ['1.567' '0.123' '5.6789' '5' '8.456' '3' '9.345']
float32 [1.567  0.123  5.6789 5.     8.456  3.     9.345 ]


In [53]:
# 실수 형식 -> 정수 값 변환은 오류 발생

num_str = '1.567 0.123 5.6789 5 8.456 3 9.345'
lst = num_str.split(' ')
arr1 = np.array(lst)
arr2 = arr1.astype(np.int32)

print(arr1.dtype, arr1)
print(arr2.dtype, arr2)

ValueError: invalid literal for int() with base 10: '1.567'

In [54]:
# 실수 형식 문자열 -> 실수 값 -> 정수 값으로 변환해야 함

num_str = '1.567 0.123 5.6789 5 8.456 3 9.345'
lst = num_str.split(' ')
arr1 = np.array(lst)
arr2 = arr1.astype(np.float32)
arr3 = arr2.astype(np.int32)

print(arr1.dtype, arr1)
print(arr2.dtype, arr2)
print(arr3.dtype, arr3)

<U6 ['1.567' '0.123' '5.6789' '5' '8.456' '3' '9.345']
float32 [1.567  0.123  5.6789 5.     8.456  3.     9.345 ]
int32 [1 0 5 5 8 3 9]


In [59]:
np.random.rand()

0.5215888016884741

In [60]:
np.random.rand(9)

array([0.20265123, 0.40470403, 0.78322432, 0.89848729, 0.66316897,
       0.24992807, 0.50201634, 0.42560705, 0.15521188])

In [61]:
np.random.rand(3, 4) # 2차원

array([[0.70036601, 0.06712067, 0.74401629, 0.34555245],
       [0.22153174, 0.88917549, 0.83927526, 0.53202945],
       [0.90294942, 0.00521963, 0.50172934, 0.361262  ]])

In [62]:
np.random.rand(2, 3, 4) # 3차원

array([[[0.05649394, 0.38162845, 0.08367894, 0.02187792],
        [0.48640527, 0.76089611, 0.19743102, 0.4245585 ],
        [0.61692475, 0.55336742, 0.77476412, 0.52668267]],

       [[0.74018005, 0.03470625, 0.2880952 , 0.32183072],
        [0.77230557, 0.79309577, 0.92003908, 0.9573297 ],
        [0.97511738, 0.89791842, 0.73452172, 0.28468961]]])

In [66]:
# python에서 가져온 randint는 범위 종료값이 포함됨
import random

random.randint(0, 3) # 0, 3이 범위에 포함됨

3

In [72]:
# numpy의 randint는 범위 종료값이 포함 안 됨
np.random.randint(0, 3) # 0은 나오지만 3은 안 나옴

0

In [76]:
np.random.randint(0, 10, size=(2, 3, 4))

array([[[7, 0, 2, 2],
        [7, 6, 8, 1],
        [9, 0, 8, 3]],

       [[4, 4, 9, 8],
        [7, 7, 0, 2],
        [3, 1, 7, 8]]])

In [77]:
# 크기가 5인 1차원 배열
np.random.randint(0, 10, size=(5,))

array([6, 2, 8, 0, 0])

In [85]:
# 중복 가능
np.random.randint(1, 46, size=(5,))

array([44, 39, 44,  5, 22])

In [86]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1 + arr2

array([11, 22, 33, 44])

In [87]:
# 연산 결과는 새로운 배열을 생성함. 기존 배열 변경X

print(arr1, arr2)

[10 20 30 40] [1 2 3 4]


In [89]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr3 = arr1 + arr2
print(arr1, arr2, arr3)

[10 20 30 40] [1 2 3 4] [11 22 33 44]


In [91]:
# 배열과 배열의 연산
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 // arr2)
print(arr1 % arr2)
print(arr1 ** arr2)
print(arr1, arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10 10 10 10]
[0 0 0 0]
[     10     400   27000 2560000]
[10 20 30 40] [1 2 3 4]


In [93]:
# 배열과 숫자의 연산
arr2 = np.array([1, 2, 3, 4])

print(arr2 + 2)
print(arr2 - 2)
print(arr2 * 2)
print(arr2 / 2)
print(arr2 // 2)
print(arr2 % 2)
print(arr2 ** 2)
print(arr2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[1 0 1 0]
[ 1  4  9 16]
[1 2 3 4]


In [95]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1 += arr2 # 복합 연산자로 바로 저장
print(arr1, arr2)

[11 22 33 44] [1 2 3 4]


In [96]:
arr2 = np.array([1, 2, 3, 4])

arr2 += 2 # 복합 대행 연산자로 바로 저장 가능
print(arr2)

[3 4 5 6]


In [98]:
# 이건 가능
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr3 = arr1 / arr2
print(arr1, arr2, arr3)

[10 20 30 40] [1 2 3 4] [10. 10. 10. 10.]


In [99]:
# 자료형 다르면 오류 발생 (나눈 결과는 실수 배열)
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1 /= arr2 # 정수 배열인 arr1, 2안에 실수 배열인 연산 결과 저장 불가 
print(arr1, arr2)

UFuncTypeError: Cannot cast ufunc 'true_divide' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [100]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1 = arr1.astype(np.float64) # 실수로 바꾼 후에 /= 사용 가능
arr1 /= arr2
print(arr1, arr2)

[10. 10. 10. 10.] [1 2 3 4]


In [101]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1 + arr2

array([11, 22, 33, 44])

In [103]:
# 배열과 배열 사이 연산에는 반드시 배열 구조가 일치해야 함
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4])

arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [104]:
# 비교 연산도 broadcast임
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr1 > arr2

array([ True,  True,  True,  True])

In [105]:
print(arr1, arr2) # 원본 배열은 변경X

[10 20 30 40] [1 2 3 4]


In [106]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

arr3 = arr1 > arr2
print(arr1, arr2, arr3)

[10 20 30 40] [1 2 3 4] [ True  True  True  True]


In [107]:
# 배열과 배열 사이 비교 연산 가능

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 > arr2)
print(arr1 < arr2)
print(arr1 >= arr2)
print(arr1 <= arr2)
print(arr1 == arr2)
print(arr1 != arr2)

[ True  True  True  True]
[False False False False]
[ True  True  True  True]
[False False False False]
[False False False False]
[ True  True  True  True]


In [109]:
# 배열과 숫자 사이 비교 연산 가능
arr2 = np.array([1, 2, 3, 4])

print(arr2 > 2)
print(arr2 < 2)
print(arr2 >= 2)
print(arr2 <= 2)
print(arr2 == 2)
print(arr2 != 2)

[False False  True  True]
[ True False False False]
[False  True  True  True]
[ True  True False False]
[False  True False False]
[ True False  True  True]


In [110]:
# 논리 연산 불가

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 and arr2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [111]:
# 논리 연산 불가

arr1 = np.array([False, False, True, True])
arr2 = np.array([False, True, False, True])

print(arr1 and arr2)

# 파이썬에서의 논리 연산자는 피연산자가 논리값이어야 하는데 arr1, arr2는 논리값이 아니라 넘피 배열이라 오류 발생

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [112]:
# Numpy에서 논리 연산하는 법
arr1 = np.array([False, False, True, True])
arr2 = np.array([False, True, False, True])

np.logical_and(arr1, arr2)

array([False, False, False,  True])

In [113]:
print(arr1, arr2) # 원본 배열은 안 바뀜

[False False  True  True] [False  True False  True]


In [114]:
# Numpy 논리 연산
arr1 = np.array([False, False, True, True])
arr2 = np.array([False, True, False, True])

print(np.logical_and(arr1, arr2)) # numpy 함수 사용
print(np.logical_or(arr1, arr2))
print(np.logical_not(arr1))
print(arr1, arr2)

[False False False  True]
[False  True  True  True]
[ True  True False False]
[False False  True  True] [False  True False  True]


In [116]:
# Numpy 자체 논리 연산자 활용

arr1 = np.array([False, False, True, True])
arr2 = np.array([False, True, False, True])

print(arr1 & arr2) # numpy 함수 사용
print(arr1 | arr2)
print(~arr1)
print(arr1, arr2)

[False False False  True]
[False  True  True  True]
[ True  True False False]
[False False  True  True] [False  True False  True]


In [ ]:
'''
문제1] 다음 리스트에 저장된 각각의 값 x에 대하여 y = 2x^3 + 4x^2 + 5x + 7의 값을 구하여
    새로운 리스트에 저장하는 코드를 작성하세요.
    단, 넘피는 사용하지 않고 파이썬으로만 코드를 작성합니다.

lst = [1, 2, 3, 4, 5]
'''

In [117]:
lst = [1, 2, 3, 4, 5]
lst2 = []

for x in lst:
    y = 2 * x ** 3 + 4 * x ** 2 + 5 * x + 7
    lst2.append(y)
    
lst2

[18, 49, 112, 219, 382]

In [ ]:
'''
문제1] 다음 리스트에 저장된 각각의 값 x에 대하여 y = 2x^3 + 4x^2 + 5x + 7의 값을 구하여
    새로운 리스트에 저장하는 코드를 작성하세요.
    단, 넘피를 사용하여 코드를 작성합니다.

lst = [1, 2, 3, 4, 5]
'''

In [119]:
arr = np.array([1, 2, 3, 4, 5])
list(2 * arr ** 3 + 4 * arr ** 2 + 5 * arr + 7)

[18, 49, 112, 219, 382]

In [120]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [121]:
print(arr.sum(), arr.mean())


10 2.0


In [122]:
print(arr.var(), arr.std())

2.0 1.4142135623730951


In [123]:
print(arr.min(), arr.max())

0 4


In [124]:
arr.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

In [125]:
arr.cumprod()

array([0, 0, 0, 0, 0], dtype=int32)

In [127]:
arr = np.arange(1, 5)
arr.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [128]:
A = np.array([0,1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [129]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [130]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [131]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [136]:
print(A)
print(B) # 원본 바뀌지 않음

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]


In [137]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [138]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [139]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [140]:
A.dot(np.linalg.inv(A)) # 행렬 dot 역행렬은 단위행렬

array([[1., 0.],
       [0., 1.]])

In [141]:
np.linalg.det(A) # 0*3 - 1*2

-2.0

In [142]:
A

array([[0, 1],
       [2, 3]])

In [143]:
# 배열을 읽고 사용하는 방법 1) 인덱싱

arr = np.array([0, 10, 20, 30, 40, 50])
arr

array([ 0, 10, 20, 30, 40, 50])

In [144]:
print(arr[0], arr[4])

0 40


In [145]:
# Numpy 배열에서도 역방향 인덱스 존재
print(arr[-1], arr[-3])

50 30


In [146]:
# arr 값 변경 가능
arr[5] = 70
arr

array([ 0, 10, 20, 30, 40, 70])

In [147]:
arr[[1, 3, 4]]

array([10, 30, 40])

In [148]:
# 파이썬은 인덱스 여러 개 안 됨
lst = [0, 10, 20, 30, 40, 50]
lst[[1, 3, 4]]

TypeError: list indices must be integers or slices, not list

In [150]:
arr = np.random.randint(10, size=(2, 2, 2))
arr

array([[[0, 7],
        [9, 0]],

       [[7, 1],
        [6, 3]]])

In [156]:
print(type(arr), type(arr[0]), type(arr[1]))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [159]:
print(type(arr[0][0]), type(arr[0][1]), type(arr[1][0]), type(arr[1][1]))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [162]:
print(type(arr[0][0][0]), type(arr[0][0][1]), type(arr[0][1][0]), type(arr[0][1][1])) # 마지막 차원만 실제 값 가짐
print(arr[0][0][0], arr[0][0][1], arr[0][1][0], arr[0][1][1])

<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
0 7 9 0


In [163]:
print(type(arr[1][0][0]), type(arr[1][0][1]), type(arr[1][1][0]), type(arr[1][1][1])) # 마지막 차원만 실제 값 가짐
print(arr[1][0][0], arr[1][0][1], arr[1][1][0], arr[1][1][1])

<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
7 1 6 3


In [164]:
arr[0][1]

array([9, 0])

In [167]:
arr = np.arange(10, 100, 10).reshape(3, 3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [169]:
# 50이 읽고 싶으면
print(arr[1][1], arr[1, 1]) # 한 단계 거치는 거(기본)랑 바로 찾는 것의 차이
# arr[1, 1]은 넘피에서만 지원

50 50


In [170]:
lst = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
print(lst[1][1])
print(lst[1, 1]) # 파이썬에서는 지원 안 됨

50


TypeError: list indices must be integers or slices, not tuple

In [ ]:
'''
문제1] 다음 배열에 저장된 값을 순서대로 출력하는 코드를 작성하세요.

arr = np.arange(10, 100, 10).reshape(3, 3)

실행결과>
10     20     30
40     50     60
70     80     90
'''

In [171]:
# 방법1. 순서번호 이용

arr = np.arange(10, 100, 10).reshape(3, 3)
for i in range(len(arr)): # 1차원 배열 3개니까 len(arr) = 3
    for j in range(len(arr[i])):
        print(arr[i][j], end='\t')
    
    print()

10	20	30	
40	50	60	
70	80	90	


In [172]:
arr = np.arange(10, 100, 10).reshape(3, 3)
for i in range(len(arr)): # 1차원 배열 3개니까 len(arr) = 3
    for j in range(len(arr[i])):
        print(arr[i, j], end='\t') # 대괄호 한꺼번에 써도 됨
    
    print()

10	20	30	
40	50	60	
70	80	90	


In [174]:
# 방법2. 컨테이너 이용(배열에서만 사용 가능)

arr = np.arange(10, 100, 10).reshape(3, 3)
for sub in arr:
    for num in sub:
        print(num, end='\t')
        
    print()

10	20	30	
40	50	60	
70	80	90	


In [ ]:
'''
문제2] 다음 리스트에 저장된 값을 순서대로 출력하는 코드를 작성하세요.

lst = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

실행결과>
10     20     30
40     50     60
70     80     90
'''

In [175]:
# 방법1. 인덱스 이용(리스트 자체에 접근)

lst = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
for i in range(len(lst)):
    for j in range(len(lst[i])):
        print(lst[i][j], end='\t')
    
    print()

10	20	30	
40	50	60	
70	80	90	


In [176]:
# 방법2. 컨테이너 이용(복사한 값을 이용)

lst = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
for sub in lst:
    for num in sub:
        print(num, end='\t')
        
    print()

10	20	30	
40	50	60	
70	80	90	


In [177]:
arr = np.arange(10, 100, 10).reshape(3, 3)
arr[2, 2] = 95
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [178]:
arr[1] = np.array([45, 65, 85])
arr

array([[10, 20, 30],
       [45, 65, 85],
       [70, 80, 95]])

In [180]:
arr[1] = [47, 57, 67] # 배열에 리스트 대입하면 암시적 형변환 발생해서 배열 됨
arr[1]

array([47, 57, 67])

In [183]:
arr = np.arange(10, 100, 10).reshape(3, 3)

print(arr[0, 0], arr[2, 1])
print(arr[[0, 2], [0, 1]]) # 파이썬 컨테이너는 지원하지 않음

10 80
[10 80]


In [185]:
# 배열을 읽고 사용하는 방법 2) 슬라이싱

arr = np.arange(0, 100, 10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [186]:
arr[1:4]

array([10, 20, 30])

In [187]:
arr[2::2] # step 사용 가능

array([20, 40, 60, 80])

In [188]:
arr[:3] # start, step 생략

array([ 0, 10, 20])

In [189]:
arr[2:] # end, step 생략

array([20, 30, 40, 50, 60, 70, 80, 90])

In [190]:
arr[-1:-7:-2]

array([90, 70, 50])

In [191]:
arr = np.arange(0, 100, 10)
arr[2:5] = np.array([25, 35, 45])
arr

array([ 0, 10, 25, 35, 45, 50, 60, 70, 80, 90])

In [192]:
arr[3:5] = 59
arr

array([ 0, 10, 25, 59, 59, 50, 60, 70, 80, 90])

In [195]:
arr = np.arange(10, 100, 10).reshape(3, 3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [196]:
arr[1:, 1:] # 두번째, 두번째

array([[50, 60],
       [80, 90]])

In [197]:
arr[:, 1:] # 전체, 두번째부터

array([[20, 30],
       [50, 60],
       [80, 90]])

In [198]:
arr = np.arange(10, 100, 10).reshape(3, 3)
arr[1][1:]

array([50, 60])

In [203]:
arr = np.arange(10, 100, 10).reshape(3, 3)
arr[:2, 1:3] = np.array([[25, 35], [55, 65]])
arr

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [204]:
# 배열을 읽고 사용하는 방법 3) 조건

arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [205]:
arr > 3

array([False, False, False,  True,  True,  True])

In [206]:
arr[[False, False, False,  True,  True,  True]]

array([4, 5, 6])

In [207]:
arr[arr > 3]

array([4, 5, 6])

In [208]:
arr % 2 == 0 # 조건

array([False,  True, False,  True, False,  True])

In [209]:
arr[arr % 2 == 0]

array([2, 4, 6])

In [210]:
'''
문제1] 다음 배열에서 [20, 50, 80], [[20, 50, 80]]을 각각 반환하는 코드를 작성하ㅔ요.

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])
'''

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [222]:
arr = np.arange(10, 100, 10).reshape(3, 3)

print(arr[:, 1]) # 슬라이싱 + 인덱싱 -> 1차원
print(arr[:, 1:2]) # 슬라이싱 + 슬라이싱 -> 2차원

[20 50 80]
[[20]
 [50]
 [80]]


In [ ]:
'''
문제2] 국어, 영어, 수학, 과학 점수를 가지는 아래의 학생 성적 정보 배열에서
수학 점수를 저장하는 3번째 열의 값이 90 이상인 학생의 정보를 출력하는 코드를 작성하세요.

[[75, 82, 95, 80],
 [85, 88, 80, 75],
 [80, 75, 90, 80],
 [85, 80, 75, 90]]

출력결과>
[[75, 82, 95, 80],
 [80, 75, 90, 80]]
'''

In [240]:
# my

arr = np.array([[75, 82, 95, 80],
 [85, 88, 80, 75],
 [80, 75, 90, 80],
 [85, 80, 75, 90]])

arr.reshape(4, 4)

arr[:, 2:3] >= 90

array([[ True],
       [False],
       [ True],
       [False]])

In [242]:
# answer
arr = np.array([[75, 82, 95, 80], [85, 88, 80, 75], [80, 75, 90, 80], [85, 80, 75, 90]])
arr[[True, False, True, False]]

array([[75, 82, 95, 80],
       [80, 75, 90, 80]])

In [245]:
arr[:, 2]

array([95, 80, 90, 75])

In [246]:
arr[:, 2] >= 90

array([ True, False,  True, False])

In [247]:
arr[arr[:, 2] >= 90]

array([[75, 82, 95, 80],
       [80, 75, 90, 80]])

In [ ]:
'''
문제3] 다음 배열에서 [[10, 30], [70, 90]] 값을 가지는 2차원 배열을 출력하는 코드를 작성하세요.

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])
'''

In [271]:
arr = np.arange(10, 100, 10).reshape(3,3)
arr = arr[[0, 2]]
arr = arr[:, [0, 2]]
arr

array([[10, 30],
       [70, 90]])

In [272]:
# 간략히
arr = np.arange(10, 100, 10).reshape(3,3)
arr[[0, 2]][:, [0, 2]]

array([[10, 30],
       [70, 90]])

In [ ]:
'''
문제4] 'data/coffee_shop_sales.txt' 파일을 읽고 다음의 결과를 출력하는 코드를 작성하세요.
        단, numpy를 사용하여 문제를 해결합니다.

[출력 결과]

에스프레소 [10, 12, 11, 15] / 총 판매량: 48, 평균 판매량: 12.0
아메리카노 [xx, xx, xx, xx] / 총 판매량: xx, 평균 판매량: xx.x
카페라떼 [xx, xx, xx, xx] / 총 판매량: xx, 평균 판매량: xx.x
카푸치노 [xx, xx, xx, xx] / 총 판매량: xx, 평균 판매량: xx.x
'''

In [302]:
# answer

with open('../data/coffee_shop_sales.txt', 'rt') as f:
    lines = f.readlines()
    
coffee_menu = lines[0].split()[1:] #1. coffee_menu 리스트 생성
coffee_menu

lines = lines[1:] #2. 커피 판매량 정보만 lines 리스트에 저장

for i in range(len(lines)):
    lines[i] = lines[i].split()[1:]

coffee_menu_sales = np.array(lines).astype(np.int32).transpose() # 3. numpy 활용

for i in range(len(coffee_menu)):
    print('%s %s / 총 판매량: %d, 평균 판매량: %.1f' % (coffee_menu[i], coffee_menu_sales[i],
                                coffee_menu_sales[i].sum(), coffee_menu_sales[i].mean())) # 4. numpy 활용하는 형태로 수정

에스프레소 [10 12 11 15] / 총 판매량: 48, 평균 판매량: 12.0
아메리카노 [50 45 53 49] / 총 판매량: 197, 평균 판매량: 49.2
카페라떼 [45 41 32 38] / 총 판매량: 156, 평균 판매량: 39.0
카푸치노 [20 18 25 22] / 총 판매량: 85, 평균 판매량: 21.2
